---
# tasks file for roles/db
- name: Pull MongoDB Docker image
  docker_image:
    name: "{{ mongo_image }}"
    source: pull

- name: Create MongoDB data volume
  docker_volume:
    name: "{{ mongo_volume_name }}"

- name: Run MongoDB Docker container
  docker_container:
    name: "{{ mongo_container_name }}"
    image: "{{ mongo_image }}"
    ports:
      -  "{{ mongo_host_port }}:{{ mongo_container_port }}"
    volumes:
      - "{{ mongo_volume_name }}:/data/db"
   
